# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-11 22:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 15, 35, 58, 824056)),
            preserve_default=False,
        ),
    ]
