# Generated by Django 2.2.1 on 2019-10-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
