# Generated by Django 2.2.1 on 2019-10-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191018_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user',
            new_name='following',
        ),
    ]
